### PR TITLE
put version numbers into changelog

### PR DESCRIPTION
**Pull request by jschleicher**
to link the corresponding pilz_robots version and know, which changes are new for subsequent releases

### CODE REVIEW

**Comment by jschleicher** [comment]
This at least documents the changes, until someone comes up with an automatic generation / check as proposed in #7.

**Review by ct2034 — CHANGES_REQUESTED** [review]
I am in favour of documentation the related releases and changes this way.
But for me, the file CHANELOG.rst is merely a release artefact. If I understand it correctly, this is only for documentation, since this package is a template and will not be released from us. I would suggest therefore to rename the file. e.g. to `changes.md` or something else. What do you think?
I mean, normally the version headers in the changelog refer to versions of the same package (`prbt_default_application` in this case) and not any other packages.

**Comment by jschleicher** [comment]
I don't get the point in changing the file name. It documents changes in the repo so its name should be CHANGELOG.{md,rst}. We could of course `git tag` versions for this templates package to refer to them - but as you said, this package should never be bloom-released. So this PR is about documenting the necessary changes how to update the template files after updating its dependencies...

**Review by ct2034 — APPROVED** [review]
I think it works this way

**Pull request merged**
